steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  dir: 'api/'
- name: 'gcr.io/cloud-builders/npm'
  args: ["run", "create-env"]
  env:
    - 'MONGODB_CONNECTION_STRING=${_MONGODB_CONNECTION_STRING}'
    - 'SERVICE_URL=${_SERVICE_URL}'
  dir: 'api/'
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy", "api/api.yaml", "-v", "$_GAE_VERSION"]
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  dir: 'client'
- name: 'gcr.io/cloud-builders/npm'
  args: ["run", "create-env"]
  env:
    - 'REACT_APP_SERVICE_URL=${_REACT_APP_SERVICE_URL}'
    - 'REACT_APP_BACKEND_URL=${_REACT_APP_BACKEND_URL}'
    - 'REACT_APP_GRAPHQL_URL=${_REACT_APP_GRAPHQL_URL}'
    - 'REACT_APP_GRAPHQL_WS_URL=${_REACT_APP_GRAPHQL_WS_URL}'
  dir: 'client/'
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
  dir: 'client'
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy", "client/client.yaml", "-v", "$_GAE_VERSION"]
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy", "client/dispatch.yaml", "-v", "$_GAE_VERSION"]
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "services", "--project", "$PROJECT_ID", "set-traffic", "--splits", "$_GAE_TRAFFIC"]
timeout: "1600s"